name: Update Version number

"on":
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: 'Update Version number'
        run: |
          git clone https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/nanos/FediFetcher.git
          cd FediFetcher
          git config user.name nanos-bot
          git config user.email bot@thms.uk
          VERSION=${{ github.ref_name }}
          VERSION="${VERSION:1}"
          sed -i -E 's/VERSION = "[0-9]+.[0-9]+.[0-9]+"/VERSION = "'$VERSION'"/' find_posts.py
          git add find_posts.py 
          git commit -m "[bot] Bump version to $VERSION"
          git push upstream HEAD:main > /dev/null 2>&1
